Repository PaulRoh97/Covid-Lunches-03, pull requests merged in 2021-04, with the labels that each got.

#86 Feature/credential config
  Covid Lunches/express/express-bootstrap/.gitignore
  Covid Lunches/express/express-bootstrap/app.js
  Covid Lunches/express/express-bootstrap/node_modules/.bin/node-sass
  Covid Lunches/express/express-bootstrap/node_modules/.bin/node-sass.cmd
  Covid Lunches/express/express-bootstrap/node_modules/.bin/node-sass.ps1
  Covid Lunches/express/express-bootstrap/options.js
Labels: Backend, Developer Story

#101 About Section
  Covid Lunches/express/express-bootstrap/public/css/style.css
  Covid Lunches/express/express-bootstrap/public/img/about-bg.jfif
  Covid Lunches/express/express-bootstrap/public/img/about-bg.jpg
  Covid Lunches/express/express-bootstrap/public/img/about.jfif
  Covid Lunches/express/express-bootstrap/public/img/about.jpg
  Covid Lunches/express/express-bootstrap/public/img/apple-touch-icon.jpg
  Covid Lunches/express/express-bootstrap/public/img/apple-touch-icon.png
  Covid Lunches/express/express-bootstrap/public/img/favicon.jpg
  Covid Lunches/express/express-bootstrap/public/img/favicon.png
  Covid Lunches/express/express-bootstrap/views/index.html
Labels: Frontend

#99 Bug/profile pic html
  Covid Lunches/express/express-bootstrap/public/css/style.css
  Covid Lunches/express/express-bootstrap/public/js/main.js
  Covid Lunches/express/express-bootstrap/public/js/profilepic.js
  Covid Lunches/express/express-bootstrap/views/index.html
Labels: bug

#125 Feature/sign up
  Covid Lunches/express/express-bootstrap/node_modules/.bin/in-install
  Covid Lunches/express/express-bootstrap/node_modules/.bin/in-publish
  Covid Lunches/express/express-bootstrap/node_modules/.bin/mime
  Covid Lunches/express/express-bootstrap/node_modules/.bin/mkdirp
  Covid Lunches/express/express-bootstrap/node_modules/.bin/node-gyp
  Covid Lunches/express/express-bootstrap/node_modules/.bin/nopt
  Covid Lunches/express/express-bootstrap/node_modules/.bin/not-in-install
  Covid Lunches/express/express-bootstrap/node_modules/.bin/not-in-publish
  Covid Lunches/express/express-bootstrap/node_modules/.bin/nunjucks-precompile
  Covid Lunches/express/express-bootstrap/node_modules/.bin/rimraf
  Covid Lunches/express/express-bootstrap/node_modules/.bin/semver
  Covid Lunches/express/express-bootstrap/node_modules/.bin/strip-indent
  Covid Lunches/express/express-bootstrap/node_modules/.bin/uuid
  Covid Lunches/express/express-bootstrap/node_modules/.bin/which
  Covid Lunches/express/express-bootstrap/node_modules/.package-lock.json
  Covid Lunches/express/express-bootstrap/node_modules/normalize-package-data/node_modules/.bin/semver
  Covid Lunches/express/express-bootstrap/package-lock.json
  Covid Lunches/express/express-bootstrap/public/css/signin.css
  Covid Lunches/express/express-bootstrap/public/css/style.css
  Covid Lunches/express/express-bootstrap/public/img/dish.svg
  Covid Lunches/express/express-bootstrap/public/js/login.js
  Covid Lunches/express/express-bootstrap/public/js/signUp.js
  Covid Lunches/express/express-bootstrap/public/js/xLogin.js
  Covid Lunches/express/express-bootstrap/routes/covid.js
  Covid Lunches/express/express-bootstrap/views/index.njk
  Covid Lunches/express/express-bootstrap/views/inner-page.njk
  Covid Lunches/express/express-bootstrap/views/login.njk
  Covid Lunches/express/express-bootstrap/views/profile-page.njk
  Covid Lunches/express/express-bootstrap/views/sign-up-student-info-page.njk
  Covid Lunches/express/express-bootstrap/views/sign-up.njk
  Covid Lunches/express/express-bootstrap/views/x-login.njk
  Covid Lunches/express/express-bootstrap/yarn.lock
Labels: Frontend

#124 Feature/picpath access
  Covid Lunches/express/express-bootstrap/public/js/main.js
  Covid Lunches/express/express-bootstrap/public/js/profilepic.js
  Covid Lunches/express/express-bootstrap/routes/covid.js
  Covid Lunches/express/express-bootstrap/views/index.njk
  Covid Lunches/express/express-bootstrap/views/inner-page.njk
Labels: Middleware

#127 Feature/pickup table
  Covid Lunches/express/express-bootstrap/public/css/style.css
  Covid Lunches/express/express-bootstrap/public/js/__test__/innerPage.test.js
  Covid Lunches/express/express-bootstrap/public/js/schedulescript.js
  Covid Lunches/express/express-bootstrap/views/inner-page.njk
Labels: Frontend, Parent, UI
